Make jaeger sender configurable
kamon-io/kamon-jaeger pull request #4
Opened 2018-01-27 08:02 UTC by milenkovicm

Add support for UDP sender and make sender type configurable.

2018-01-27 11:46 UTC, ivantopo requested changes
Didn't try running it just yet but looks nice. Btw, what are you using to format the code? there are a few things that look nicer but some others like line 23 and 124 where it just breaks the old style.

2018-01-27 11:46 UTC, ivantopo commented on src/main/scala/kamon/jaeger/JaegerReporter.scala
> +      case "http" | _ ⇒
It would be nice to have a error message when the setting isn't udp/http and just failing to load the reporter. Since the default is HTTP users will only touch this key when they want to change and if they had a typo there it should be known. Btw, please lowercase the `jaegerSender` setting above before matching to reduce chances of problems.

2018-01-27 12:06 UTC, milenkovicm commented
Will revert code style, I’ve released what I did when I pushed pull request. But I left it open to kick discussion about the change I want to merge. Will push th changes a bit later

2018-01-27 12:53 UTC, milenkovicm commented
updated now, please have a look when you get a chance. 
if unknown sender is configured it will leave `jaegerClient` uninitialised and print error (I'm not sure should it be error or warning)

2018-01-30 17:03 UTC, milenkovicm commented
There is issue with UDP Reporter I'm investigating at the moment
```
org.apache.thrift.transport.TTransportException: Message size too large: 1 > 65000
	at com.uber.jaeger.reporters.protocols.ThriftUdpTransport.write(ThriftUdpTransport.java:139)
	at org.apache.thrift.transport.TTransport.write(TTransport.java:107)
	at org.apache.thrift.protocol.TCompactProtocol.writeByteDirect(TCompactProtocol.java:482)
	at org.apache.thrift.protocol.TCompactProtocol.writeMessageBegin(TCompactProtocol.java:198)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62)
	at com.uber.jaeger.agent.thrift.Agent$Client.send_emitBatch(Agent.java:97)
	at com.uber.jaeger.agent.thrift.Agent$Client.emitBatch(Agent.java:90)
	at com.uber.jaeger.senders.UdpSender.send(UdpSender.java:60)
	at kamon.jaeger.JaegerClient.sendSpans(JaegerReporter.scala:77)
	at kamon.jaeger.JaegerReporter.reportSpans(JaegerReporter.scala:66)
	at kamon.ReporterRegistry$Default$SpanReporterTicker.$anonfun$run$9(ReporterRegistry.scala:384)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.Try$.apply(Try.scala:209)
	at kamon.ReporterRegistry$Default$SpanReporterTicker.$anonfun$run$8(ReporterRegistry.scala:384)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:655)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run_aroundBody0(Promise.scala:60)
	at scala.concurrent.impl.CallbackRunnable$AjcClosure1.run(Promise.scala:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at kamon.scala.instrumentation.FutureInstrumentation.$anonfun$aroundExecution$1(FutureInstrumentation.scala:46)
	at kamon.Kamon$.withContext(Kamon.scala:120)
	at kamon.scala.instrumentation.FutureInstrumentation.aroundExecution(FutureInstrumentation.scala:46)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

2018-02-01 01:21 UTC, ivantopo commented
Hey @milenkovicm, when are you getting this error? right after starting of after sending a few Spans to Jaeger? I took a very quick look at the jaeger client code and _maybe_ it has to do with the transport not flushing the data but that's a wild guess. 

Please tell me if you need some help on this or you could also drop them a message in the [Jaeger channel on Gitter](https://gitter.im/jaegertracing/Lobby).

2018-02-01 10:04 UTC, milenkovicm commented
Hi @ivantopo, 
I believe there is a problem with jaeger client, as well. I've opened them a bug jaegertracing/jaeger-client-java#328

I'm a bit busy at the moment but will ping them later, thanks for your help

2018-03-23 10:38 UTC, ivantopo commented
Hey Marko, I took a look at the related issues on the Jaeger client, but still no news :(... I added this "stalled" label just for information purposes. Hopefully it will be eventually solved, thanks!

2018-03-23 10:41 UTC, milenkovicm commented
No problem. I'll close it if there is no changes in near future.

2018-08-22 06:06 UTC, ivantopo commented
Hey man, the upstream issue remains unresolved. I'm going to close this PR and maybe down the road if they fix it we can reopen it. Thanks for the effort anyways!

2018-08-22 06:06 UTC, closed without merging